config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  resources :flights, only: %i[index show]
  resources :bookings, only: %i[new create show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departures, class_name: "Flight", foreign_key: :origin_port_id
  has_many :arrivals, class_name: "Flight", foreign_key: :destination_port_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_and_belongs_to_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :origin_port, class_name: "Airport"
  belongs_to :destination_port, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings

  def formatted_date
    date.strftime("%m/%d/%Y")
  end

  def flight_details
    "Departing: #{self.origin_port.code}\n
    Arriving: #{self.destination_port.code}\n
    Flight date: #{self.formatted_date}\n
    Flight duration: #{self.duration} minutes"
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_and_belongs_to_many :bookings
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @flight_selection = Flight.find(params[:selection][:flight_selection])
    @booking = Booking.new
    params[:selection][:no_of_passengers].to_i.times { @booking.passengers.build }
  end

  def create
    @flight_selection = Flight.find(params[:booking][:flight_id])
    @booking = Booking.new(booking_params)

    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.with(passenger: passenger).thank_you_email.deliver_now
      end

      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  
  
  def index
    if params[:commit].nil?
      @flights = Flight.all
    else
      @flights = search_results
    end
  end

  def show
    @flight = Flight.find(params[:id])
  end

  private

  def search_results
    if flight_params[:date] == ""
      Flight.where(origin_port_id: flight_params[:origin_port_id], destination_port_id: flight_params[:destination_port_id])
    else
      Flight.where(origin_port_id: flight_params[:origin_port_id], destination_port_id: flight_params[:destination_port_id], date: flight_params[:date])
    end
  end

  def flight_params
    params.permit(:origin_port_id, :destination_port_id, :date, :no_of_passengers)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/new.html.erb
<div class="flex-container">

  <div class="search-bar">
    <h1>Booking details</h1>
    <%= form_with model: @booking do |form| %>
      <%= form.hidden_field :no_of_passengers, value: params[:selection][:no_of_passengers] %>
      <%= form.hidden_field :flight_id, value: params[:selection][:flight_selection] %>
      
      <div class="booking-container">
        <p>Departing: <%= @flight_selection.origin_port.code %></p>
        <p>Arriving: <%= @flight_selection.destination_port.code %></p>
        <p>Flight date: <%= @flight_selection.formatted_date %></p>
        <p>Flight duration: <%= @flight_selection.duration %> minutes</p>
      </div>

      Passenger information:
      <ul>
        <%= form.fields_for :passengers do |p| %>
          <li>
            <%= p.label :name %>
            <%= p.text_field :name %>
            
            <%= p.label :email %>
            <%= p.text_field :email%>
          </li>
        <% end %>
      </ul>

      <%= form.submit "Confirm booking" %>
    <% end %>
  </div>

</div>

app/views/bookings/show.html.erb
<div class="flex-container">

  <div class="feed">

    <h1>Booking details</h1>

    <h2>Your Flight:</h2>
    <div class="booking-container">
      <p>Departing: <%= @booking.flight.origin_port.code %></p>
      <p>Arriving: <%= @booking.flight.destination_port.code %></p>
      <p>Flight date: <%= @booking.flight.formatted_date %></p>
      <p>Flight duration: <%= @booking.flight.duration %> minutes</p>
    </div>

    <h2>Passengers:</h2>
    <% @booking.passengers.each do |passenger| %>
      <div class="booking-container">
        <p>Name: <%= passenger.name %></p>
        <p>Email: <%= passenger.email %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/flights/_feed.html.erb
<div class="feed">
  <div class="search-form">
    <h1>Select a flight:</h1>

    <%= form_with url: new_booking_path, scope: :selection,  method: :get do |form| %>
      <%= form.hidden_field :no_of_passengers, value: params[:no_of_passengers] %>

      <div class="form-field">
        <%= form.collection_radio_buttons :flight_selection, @flights.order(:date), :id, :flight_details do |b| %>
          <div class="flight-container">
            <p class="radio-label"><%= b.label %></p>
            <p><%= b.radio_button %></p>
          </div>
        <% end %>
      </div>

      <div class="form-field">
        <%= form.submit "Book now" %>
      </div>

    <% end%>

  </div>
</div>

app/views/flights/_search_form.html.erb
<div class="search-bar">
    <h1>Search for flights:</h1>
    <%= form_with model: @flight, method: :get do |form| %>
      <div class="form-field">
        <%= form.label :origin_port_id, "FROM" %>
        <%= form.collection_select :origin_port_id, Airport.order(:id), :id, :city %>
      </div>
      <div class="form-field">
        <%= form.label :destination_port_id, "TO" %>
        <%= form.collection_select :destination_port_id, Airport.order(:id), :id, :city %>
      </div>
      <div class="form-field">
        <%= form.label :date, "DATE" %>
        <%= form.collection_select :date, Flight.select(:date).distinct.order(:date), :date, :formatted_date, { include_blank: true } %>
      </div>
      <div class="form-field">
        <%= form.label :no_of_passengers, "Passengers" %>
        <%= form.select :no_of_passengers, [1, 2, 3, 4] %>
      </div>
      <div class="form-field">
        <%= form.submit "Find Flights" %>
      </div>
    <% end %>
  </div>

app/views/flights/index.html.erb
<div class="flex-container">

  <%= render "search_form" %>

  <% if params[:commit] %>
    <% if @flights.empty? %>
      <p>Sorry, no results matched your search.</p>
    <% else %>
      <%= render "feed" %>
    <% end %>
  <% end %>
    
</div>

app/views/flights/show.html.erb
<h1>Flights#show</h1>
<p>Find me in app/views/flights/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Elysian Airlines</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar">
      <div class="navbar-item">
        <h1 class="home"><%= link_to "Elysian Airlines", root_path %></h1>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>